In [1]:
import pandas as pd

In [3]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
     ------------------------------------ 250.9/250.9 kB 615.5 kB/s eta 0:00:00
Collecting et-xmlfile
  Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
df = pd.read_excel("ins.xlsx")

In [5]:
df

,S.No.,OrderDate,Region,Manager,SalesMan,Item,Units,Unit_price,Sale_amt
0,1,2019-08-07,Central,Hermann,Shelli,Video Games,42.0,58.5,2457.0
1,2,2019-08-24,West,Timothy,Stephen,Desk,3.0,125.0,375.0
2,3,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
3,4,2018-01-06,East,Martha,Alexander,Television,95.0,1198.0,113810.0
4,5,2018-01-23,Central,Hermann,Shelli,Home Theater,50.0,500.0,25000.0
5,6,2018-02-09,Central,Hermann,Luis,Television,36.0,1198.0,43128.0
6,7,2018-02-26,Central,NaN,David,Cell Phone,27.0,225.0,6075.0
7,8,2018-03-15,West,Timothy,Stephen,Television,NaN,1198.0,0.0
8,9,2018-04-01,East,Martha,Alexander,Home Theater,60.0,500.0,30000.0
9,10,2018-04-18,NaN,Martha,Steven,Television,75.0,1198.0,89850.0
10,11,2018-05-05,Central,Hermann,NaN,Television,90.0,1198.0,107820.0
11,12,2018-05-22,West,Douglas,Michael,Television,32.0,1198.0,38336.0
12,13,2018-06-08,East,Martha,Alexander,Home Theater,60.0,500.0,30000.0
13,14,2018-06-25,Central,Hermann,Sigal,Television,90.0,1198.0,107820.0
14,15,2018-07-12,East,Martha,Diana,Home Theater,29.0,500.0,14500.0
15,16,2018-07-29,NaN,Douglas,Karen,Home Theater,81.0,500.0,40500.0
16,17,2018-08-15,East,Martha,Alexander,NaN,35.0,1198.0,41930.0
17,18,2018-09-01,Central,Douglas,John,Desk,2.0,125.0,250.0
18,19,2018-09-18,East,Martha,Alexander,Video Games,16.0,58.5,936.0
19,20,2018-10-05,Central,Hermann,Sigal,Home Theater,28.0,500.0,14000.0
20,21,2018-10-22,East,Martha,Alexander,Cell Phone,64.0,225.0,14400.0
21,22,2018-11-08,East,Douglas,Karen,Cell Phone,15.0,225.0,3375.0
22,23,2018-11-25,Central,Hermann,Shelli,Video Games,96.0,58.5,5616.0
23,24,2018-12-12,Central,Douglas,John,Television,67.0,1198.0,80266.0
24,25,2018-12-29,East,Douglas,Karen,NaN,74.0,58.5,4329.0
25,26,2019-01-15,Central,Timothy,David,Home Theater,46.0,500.0,23000.0
26,27,2019-02-01,Central,Douglas,John,Home Theater,87.0,500.0,43500.0
27,28,2019-02-18,East,Martha,Alexander,Home Theater,4.0,500.0,2000.0
28,29,2019-03-07,West,Timothy,Stephen,Home Theater,7.0,500.0,3500.0
29,30,2019-03-24,Central,Hermann,Luis,Video Games,50.0,58.5,2925.0
30,31,2019-04-10,Central,Martha,Steven,Television,NaN,1198.0,0.0
31,32,2019-04-27,East,Martha,Diana,Cell Phone,96.0,225.0,21600.0
32,33,2019-05-14,Central,Timothy,David,Television,53.0,1198.0,63494.0
33,34,2019-05-31,Central,Timothy,David,Home Theater,80.0,500.0,40000.0
34,35,2019-06-17,Central,Hermann,Shelli,Desk,5.0,125.0,625.0
35,36,2019-07-04,East,Martha,Alexander,Video Games,NaN,58.5,0.0
36,37,2019-07-21,Central,Hermann,Sigal,Video Games,55.0,58.5,3217.5
37,38,2019-08-07,Central,Hermann,NaN,Video Games,42.0,58.5,2457.0
38,39,2019-08-24,West,Timothy,Stephen,Desk,3.0,125.0,375.0
39,40,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
40,41,2019-09-27,West,Timothy,Stephen,Cell Phone,76.0,225.0,17100.0
41,42,2019-10-14,West,Douglas,Michael,Home Theater,57.0,500.0,28500.0
42,43,2019-10-31,Central,Martha,Steven,Television,14.0,1198.0,16772.0
43,44,2019-11-17,Central,Hermann,Luis,Home Theater,11.0,500.0,5500.0
44,45,2019-12-04,Central,Hermann,Luis,Home Theater,94.0,500.0,47000.0
45,46,2019-12-21,Central,Martha,Steven,Home Theater,28.0,500.0,14000.0
46,47,2019-04-27,East,Martha,Diana,Cell Phone,96.0,225.0,21600.0
47,48,2019-02-01,Central,Douglas,John,Home Theater,87.0,500.0,43500.0
48,49,2019-03-24,Central,Hermann,Luis,Video Games,50.0,58.5,2925.0
49,50,2019-04-10,Central,Martha,Steven,Television,66.0,1198.0,79068.0
50,51,2019-04-27,East,Martha,Diana,Cell Phone,96.0,225.0,21600.0
51,52,2019-05-14,Central,Timothy,David,Television,53.0,1198.0,63494.0

In [11]:
df.head()

,S.No.,OrderDate,Region,Manager,SalesMan,Item,Units,Unit_price,Sale_amt
0,1,2019-08-07,Central,Hermann,Shelli,Video Games,42.0,58.5,2457.0
1,2,2019-08-24,West,Timothy,Stephen,Desk,3.0,125.0,375.0
2,3,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
3,4,2018-01-06,East,Martha,Alexander,Television,95.0,1198.0,113810.0
4,5,2018-01-23,Central,Hermann,Shelli,Home Theater,50.0,500.0,25000.0

# Filtering Unique Values

In [8]:
df.Region.unique()

array(['Central', 'West', 'East', nan], dtype=object)

In [9]:
df.Manager.unique()

array(['Hermann', 'Timothy', 'Martha', nan, 'Douglas'], dtype=object)

In [10]:
df.SalesMan.unique()

array(['Shelli', 'Stephen', 'David', 'Alexander', 'Luis', 'Steven', nan,
       'Michael', 'Sigal', 'Diana', 'Karen', 'John'], dtype=object)

In [16]:
df.Item.unique()

array(['Video Games', 'Desk', 'Television', 'Home Theater', 'Cell Phone',
       nan], dtype=object)

### All Sales From Central

In [19]:
df[df.Region == "Central"]

,S.No.,OrderDate,Region,Manager,SalesMan,Item,Units,Unit_price,Sale_amt
0,1,2019-08-07,Central,Hermann,Shelli,Video Games,42.0,58.5,2457.0
2,3,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
4,5,2018-01-23,Central,Hermann,Shelli,Home Theater,50.0,500.0,25000.0
5,6,2018-02-09,Central,Hermann,Luis,Television,36.0,1198.0,43128.0
6,7,2018-02-26,Central,NaN,David,Cell Phone,27.0,225.0,6075.0
10,11,2018-05-05,Central,Hermann,NaN,Television,90.0,1198.0,107820.0
13,14,2018-06-25,Central,Hermann,Sigal,Television,90.0,1198.0,107820.0
17,18,2018-09-01,Central,Douglas,John,Desk,2.0,125.0,250.0
19,20,2018-10-05,Central,Hermann,Sigal,Home Theater,28.0,500.0,14000.0
22,23,2018-11-25,Central,Hermann,Shelli,Video Games,96.0,58.5,5616.0
23,24,2018-12-12,Central,Douglas,John,Television,67.0,1198.0,80266.0
25,26,2019-01-15,Central,Timothy,David,Home Theater,46.0,500.0,23000.0
26,27,2019-02-01,Central,Douglas,John,Home Theater,87.0,500.0,43500.0
29,30,2019-03-24,Central,Hermann,Luis,Video Games,50.0,58.5,2925.0
30,31,2019-04-10,Central,Martha,Steven,Television,NaN,1198.0,0.0
32,33,2019-05-14,Central,Timothy,David,Television,53.0,1198.0,63494.0
33,34,2019-05-31,Central,Timothy,David,Home Theater,80.0,500.0,40000.0
34,35,2019-06-17,Central,Hermann,Shelli,Desk,5.0,125.0,625.0
36,37,2019-07-21,Central,Hermann,Sigal,Video Games,55.0,58.5,3217.5
37,38,2019-08-07,Central,Hermann,NaN,Video Games,42.0,58.5,2457.0
39,40,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
42,43,2019-10-31,Central,Martha,Steven,Television,14.0,1198.0,16772.0
43,44,2019-11-17,Central,Hermann,Luis,Home Theater,11.0,500.0,5500.0
44,45,2019-12-04,Central,Hermann,Luis,Home Theater,94.0,500.0,47000.0
45,46,2019-12-21,Central,Martha,Steven,Home Theater,28.0,500.0,14000.0
47,48,2019-02-01,Central,Douglas,John,Home Theater,87.0,500.0,43500.0
48,49,2019-03-24,Central,Hermann,Luis,Video Games,50.0,58.5,2925.0
49,50,2019-04-10,Central,Martha,Steven,Television,66.0,1198.0,79068.0
51,52,2019-05-14,Central,Timothy,David,Television,53.0,1198.0,63494.0

In [25]:
df

,S.No.,OrderDate,Region,Manager,SalesMan,Item,Units,Unit_price,Sale_amt
0,1,2019-08-07,Central,Hermann,Shelli,Video Games,42.0,58.5,2457.0
1,2,2019-08-24,West,Timothy,Stephen,Desk,3.0,125.0,375.0
2,3,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
3,4,2018-01-06,East,Martha,Alexander,Television,95.0,1198.0,113810.0
4,5,2018-01-23,Central,Hermann,Shelli,Home Theater,50.0,500.0,25000.0
5,6,2018-02-09,Central,Hermann,Luis,Television,36.0,1198.0,43128.0
6,7,2018-02-26,Central,NaN,David,Cell Phone,27.0,225.0,6075.0
7,8,2018-03-15,West,Timothy,Stephen,Television,NaN,1198.0,0.0
8,9,2018-04-01,East,Martha,Alexander,Home Theater,60.0,500.0,30000.0
9,10,2018-04-18,NaN,Martha,Steven,Television,75.0,1198.0,89850.0
10,11,2018-05-05,Central,Hermann,NaN,Television,90.0,1198.0,107820.0
11,12,2018-05-22,West,Douglas,Michael,Television,32.0,1198.0,38336.0
12,13,2018-06-08,East,Martha,Alexander,Home Theater,60.0,500.0,30000.0
13,14,2018-06-25,Central,Hermann,Sigal,Television,90.0,1198.0,107820.0
14,15,2018-07-12,East,Martha,Diana,Home Theater,29.0,500.0,14500.0
15,16,2018-07-29,NaN,Douglas,Karen,Home Theater,81.0,500.0,40500.0
16,17,2018-08-15,East,Martha,Alexander,NaN,35.0,1198.0,41930.0
17,18,2018-09-01,Central,Douglas,John,Desk,2.0,125.0,250.0
18,19,2018-09-18,East,Martha,Alexander,Video Games,16.0,58.5,936.0
19,20,2018-10-05,Central,Hermann,Sigal,Home Theater,28.0,500.0,14000.0
20,21,2018-10-22,East,Martha,Alexander,Cell Phone,64.0,225.0,14400.0
21,22,2018-11-08,East,Douglas,Karen,Cell Phone,15.0,225.0,3375.0
22,23,2018-11-25,Central,Hermann,Shelli,Video Games,96.0,58.5,5616.0
23,24,2018-12-12,Central,Douglas,John,Television,67.0,1198.0,80266.0
24,25,2018-12-29,East,Douglas,Karen,NaN,74.0,58.5,4329.0
25,26,2019-01-15,Central,Timothy,David,Home Theater,46.0,500.0,23000.0
26,27,2019-02-01,Central,Douglas,John,Home Theater,87.0,500.0,43500.0
27,28,2019-02-18,East,Martha,Alexander,Home Theater,4.0,500.0,2000.0
28,29,2019-03-07,West,Timothy,Stephen,Home Theater,7.0,500.0,3500.0
29,30,2019-03-24,Central,Hermann,Luis,Video Games,50.0,58.5,2925.0
30,31,2019-04-10,Central,Martha,Steven,Television,NaN,1198.0,0.0
31,32,2019-04-27,East,Martha,Diana,Cell Phone,96.0,225.0,21600.0
32,33,2019-05-14,Central,Timothy,David,Television,53.0,1198.0,63494.0
33,34,2019-05-31,Central,Timothy,David,Home Theater,80.0,500.0,40000.0
34,35,2019-06-17,Central,Hermann,Shelli,Desk,5.0,125.0,625.0
35,36,2019-07-04,East,Martha,Alexander,Video Games,NaN,58.5,0.0
36,37,2019-07-21,Central,Hermann,Sigal,Video Games,55.0,58.5,3217.5
37,38,2019-08-07,Central,Hermann,NaN,Video Games,42.0,58.5,2457.0
38,39,2019-08-24,West,Timothy,Stephen,Desk,3.0,125.0,375.0
39,40,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
40,41,2019-09-27,West,Timothy,Stephen,Cell Phone,76.0,225.0,17100.0
41,42,2019-10-14,West,Douglas,Michael,Home Theater,57.0,500.0,28500.0
42,43,2019-10-31,Central,Martha,Steven,Television,14.0,1198.0,16772.0
43,44,2019-11-17,Central,Hermann,Luis,Home Theater,11.0,500.0,5500.0
44,45,2019-12-04,Central,Hermann,Luis,Home Theater,94.0,500.0,47000.0
45,46,2019-12-21,Central,Martha,Steven,Home Theater,28.0,500.0,14000.0
46,47,2019-04-27,East,Martha,Diana,Cell Phone,96.0,225.0,21600.0
47,48,2019-02-01,Central,Douglas,John,Home Theater,87.0,500.0,43500.0
48,49,2019-03-24,Central,Hermann,Luis,Video Games,50.0,58.5,2925.0
49,50,2019-04-10,Central,Martha,Steven,Television,66.0,1198.0,79068.0
50,51,2019-04-27,East,Martha,Diana,Cell Phone,96.0,225.0,21600.0
51,52,2019-05-14,Central,Timothy,David,Television,53.0,1198.0,63494.0

# Total Sales from West

In [ ]:
df[df.Region == "East"]["Sale_amt"].sum()

Empty DataFrame
Columns: [S.No., OrderDate, Region, Manager, SalesMan, Item, Units, Unit_price, Sale_amt]
Index: []

# Total Television Sales in East:

In [33]:
df[(df.Region == "East")&(df.Item == "Television")]

,S.No.,OrderDate,Region,Manager,SalesMan,Item,Units,Unit_price,Sale_amt
3,4,2018-01-06,East,Martha,Alexander,Television,95.0,1198.0,113810.0

In [36]:
df.head()

,S.No.,OrderDate,Region,Manager,SalesMan,Item,Units,Unit_price,Sale_amt
0,1,2019-08-07,Central,Hermann,Shelli,Video Games,42.0,58.5,2457.0
1,2,2019-08-24,West,Timothy,Stephen,Desk,3.0,125.0,375.0
2,3,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
3,4,2018-01-06,East,Martha,Alexander,Television,95.0,1198.0,113810.0
4,5,2018-01-23,Central,Hermann,Shelli,Home Theater,50.0,500.0,25000.0

### Number of cellphones sold by alexander in central

In [46]:
df[(df.Region == "Central")&(df.SalesMan == "David")&(df.Item == "Cell Phone")]

,S.No.,OrderDate,Region,Manager,SalesMan,Item,Units,Unit_price,Sale_amt
6,7,2018-02-26,Central,NaN,David,Cell Phone,27.0,225.0,6075.0

## John and Diana Total sales of video games in central

In [59]:
df[(df.Region == "Central")&(df.SalesMan.isin(["Diana","John"]))&(df.Item == "Video Games")]

Empty DataFrame
Columns: [S.No., OrderDate, Region, Manager, SalesMan, Item, Units, Unit_price, Sale_amt]
Index: []

In [ ]:
df[(df.Region == "Central")&(df.SalesMan == "John") | (df.SalesMan == "Alexander")&(df.Item == "Video Games")]

,S.No.,OrderDate,Region,Manager,SalesMan,Item,Units,Unit_price,Sale_amt
17,18,2018-09-01,Central,Douglas,John,Desk,2.0,125.0,250.0
18,19,2018-09-18,East,Martha,Alexander,Video Games,16.0,58.5,936.0
23,24,2018-12-12,Central,Douglas,John,Television,67.0,1198.0,80266.0
26,27,2019-02-01,Central,Douglas,John,Home Theater,87.0,500.0,43500.0
35,36,2019-07-04,East,Martha,Alexander,Video Games,NaN,58.5,0.0
47,48,2019-02-01,Central,Douglas,John,Home Theater,87.0,500.0,43500.0

In [65]:
df[(df.Region == "Central")&(df.SalesMan == "John")]

,S.No.,OrderDate,Region,Manager,SalesMan,Item,Units,Unit_price,Sale_amt
17,18,2018-09-01,Central,Douglas,John,Desk,2.0,125.0,250.0
23,24,2018-12-12,Central,Douglas,John,Television,67.0,1198.0,80266.0
26,27,2019-02-01,Central,Douglas,John,Home Theater,87.0,500.0,43500.0
47,48,2019-02-01,Central,Douglas,John,Home Theater,87.0,500.0,43500.0

In [66]:
df

,S.No.,OrderDate,Region,Manager,SalesMan,Item,Units,Unit_price,Sale_amt
0,1,2019-08-07,Central,Hermann,Shelli,Video Games,42.0,58.5,2457.0
1,2,2019-08-24,West,Timothy,Stephen,Desk,3.0,125.0,375.0
2,3,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
3,4,2018-01-06,East,Martha,Alexander,Television,95.0,1198.0,113810.0
4,5,2018-01-23,Central,Hermann,Shelli,Home Theater,50.0,500.0,25000.0
5,6,2018-02-09,Central,Hermann,Luis,Television,36.0,1198.0,43128.0
6,7,2018-02-26,Central,NaN,David,Cell Phone,27.0,225.0,6075.0
7,8,2018-03-15,West,Timothy,Stephen,Television,NaN,1198.0,0.0
8,9,2018-04-01,East,Martha,Alexander,Home Theater,60.0,500.0,30000.0
9,10,2018-04-18,NaN,Martha,Steven,Television,75.0,1198.0,89850.0
10,11,2018-05-05,Central,Hermann,NaN,Television,90.0,1198.0,107820.0
11,12,2018-05-22,West,Douglas,Michael,Television,32.0,1198.0,38336.0
12,13,2018-06-08,East,Martha,Alexander,Home Theater,60.0,500.0,30000.0
13,14,2018-06-25,Central,Hermann,Sigal,Television,90.0,1198.0,107820.0
14,15,2018-07-12,East,Martha,Diana,Home Theater,29.0,500.0,14500.0
15,16,2018-07-29,NaN,Douglas,Karen,Home Theater,81.0,500.0,40500.0
16,17,2018-08-15,East,Martha,Alexander,NaN,35.0,1198.0,41930.0
17,18,2018-09-01,Central,Douglas,John,Desk,2.0,125.0,250.0
18,19,2018-09-18,East,Martha,Alexander,Video Games,16.0,58.5,936.0
19,20,2018-10-05,Central,Hermann,Sigal,Home Theater,28.0,500.0,14000.0
20,21,2018-10-22,East,Martha,Alexander,Cell Phone,64.0,225.0,14400.0
21,22,2018-11-08,East,Douglas,Karen,Cell Phone,15.0,225.0,3375.0
22,23,2018-11-25,Central,Hermann,Shelli,Video Games,96.0,58.5,5616.0
23,24,2018-12-12,Central,Douglas,John,Television,67.0,1198.0,80266.0
24,25,2018-12-29,East,Douglas,Karen,NaN,74.0,58.5,4329.0
25,26,2019-01-15,Central,Timothy,David,Home Theater,46.0,500.0,23000.0
26,27,2019-02-01,Central,Douglas,John,Home Theater,87.0,500.0,43500.0
27,28,2019-02-18,East,Martha,Alexander,Home Theater,4.0,500.0,2000.0
28,29,2019-03-07,West,Timothy,Stephen,Home Theater,7.0,500.0,3500.0
29,30,2019-03-24,Central,Hermann,Luis,Video Games,50.0,58.5,2925.0
30,31,2019-04-10,Central,Martha,Steven,Television,NaN,1198.0,0.0
31,32,2019-04-27,East,Martha,Diana,Cell Phone,96.0,225.0,21600.0
32,33,2019-05-14,Central,Timothy,David,Television,53.0,1198.0,63494.0
33,34,2019-05-31,Central,Timothy,David,Home Theater,80.0,500.0,40000.0
34,35,2019-06-17,Central,Hermann,Shelli,Desk,5.0,125.0,625.0
35,36,2019-07-04,East,Martha,Alexander,Video Games,NaN,58.5,0.0
36,37,2019-07-21,Central,Hermann,Sigal,Video Games,55.0,58.5,3217.5
37,38,2019-08-07,Central,Hermann,NaN,Video Games,42.0,58.5,2457.0
38,39,2019-08-24,West,Timothy,Stephen,Desk,3.0,125.0,375.0
39,40,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
40,41,2019-09-27,West,Timothy,Stephen,Cell Phone,76.0,225.0,17100.0
41,42,2019-10-14,West,Douglas,Michael,Home Theater,57.0,500.0,28500.0
42,43,2019-10-31,Central,Martha,Steven,Television,14.0,1198.0,16772.0
43,44,2019-11-17,Central,Hermann,Luis,Home Theater,11.0,500.0,5500.0
44,45,2019-12-04,Central,Hermann,Luis,Home Theater,94.0,500.0,47000.0
45,46,2019-12-21,Central,Martha,Steven,Home Theater,28.0,500.0,14000.0
46,47,2019-04-27,East,Martha,Diana,Cell Phone,96.0,225.0,21600.0
47,48,2019-02-01,Central,Douglas,John,Home Theater,87.0,500.0,43500.0
48,49,2019-03-24,Central,Hermann,Luis,Video Games,50.0,58.5,2925.0
49,50,2019-04-10,Central,Martha,Steven,Television,66.0,1198.0,79068.0
50,51,2019-04-27,East,Martha,Diana,Cell Phone,96.0,225.0,21600.0
51,52,2019-05-14,Central,Timothy,David,Television,53.0,1198.0,63494.0

In [85]:
df.head()

,S.No.,OrderDate,Region,Manager,SalesMan,Item,Units,Unit_price,Sale_amt
0,1,2019-08-07,Central,Hermann,Shelli,Video Games,42.0,58.5,2457.0
1,2,2019-08-24,West,Timothy,Stephen,Desk,3.0,125.0,375.0
2,3,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
3,4,2018-01-06,East,Martha,Alexander,Television,95.0,1198.0,113810.0
4,5,2018-01-23,Central,Hermann,Shelli,Home Theater,50.0,500.0,25000.0

In [73]:
df.groupby('Region')['Sale_amt'].sum()

Region
Central    860681.5
East       320080.0
West        88186.0
Name: Sale_amt, dtype: float64

In [84]:
df.groupby("Item")["Sale_amt"].sum()

Item
Cell Phone      105750.0
Desk              1625.0
Home Theater    404500.0
Television      820630.0
Video Games      20533.5
Name: Sale_amt, dtype: float64

## Find The Top 3 WORST SalesMan According to their Sales Amount

In [100]:
df.groupby("SalesMan")["Sale_amt"].sum().sort_values().head(3)

SalesMan
Stephen    21350.0
Shelli     33698.0
Karen      48204.0
Name: Sale_amt, dtype: float64

In [103]:
b = df.groupby("SalesMan")["Sale_amt"].sum().sort_values()
b.iloc[[0,1,2]]

SalesMan
Stephen    21350.0
Shelli     33698.0
Karen      48204.0
Name: Sale_amt, dtype: float64

In [106]:
df.groupby("SalesMan")["Sale_amt"].agg(["sum","mean","median"])

                sum          mean   median
SalesMan
Alexander  233076.0  29134.500000  22200.0
David      212835.0  30405.000000  23000.0
Diana       79300.0  19825.000000  21600.0
John       167516.0  41879.000000  43500.0
Karen       48204.0  16068.000000   4329.0
Luis       101478.0  20295.600000   5500.0
Michael     66836.0  33418.000000  33418.0
Shelli      33698.0   8424.500000   4036.5
Sigal      125037.5  41679.166667  14000.0
Stephen     21350.0   4270.000000    375.0
Steven     199690.0  39938.000000  16772.0

In [107]:
df.head(10)

,S.No.,OrderDate,Region,Manager,SalesMan,Item,Units,Unit_price,Sale_amt
0,1,2019-08-07,Central,Hermann,Shelli,Video Games,42.0,58.5,2457.0
1,2,2019-08-24,West,Timothy,Stephen,Desk,3.0,125.0,375.0
2,3,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
3,4,2018-01-06,East,Martha,Alexander,Television,95.0,1198.0,113810.0
4,5,2018-01-23,Central,Hermann,Shelli,Home Theater,50.0,500.0,25000.0
5,6,2018-02-09,Central,Hermann,Luis,Television,36.0,1198.0,43128.0
6,7,2018-02-26,Central,NaN,David,Cell Phone,27.0,225.0,6075.0
7,8,2018-03-15,West,Timothy,Stephen,Television,NaN,1198.0,0.0
8,9,2018-04-01,East,Martha,Alexander,Home Theater,60.0,500.0,30000.0
9,10,2018-04-18,NaN,Martha,Steven,Television,75.0,1198.0,89850.0

In [123]:
df[df.SalesMan == "David"]

,S.No.,OrderDate,Region,Manager,SalesMan,Item,Units,Unit_price,Sale_amt
2,3,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
6,7,2018-02-26,Central,NaN,David,Cell Phone,27.0,225.0,6075.0
25,26,2019-01-15,Central,Timothy,David,Home Theater,46.0,500.0,23000.0
32,33,2019-05-14,Central,Timothy,David,Television,53.0,1198.0,63494.0
33,34,2019-05-31,Central,Timothy,David,Home Theater,80.0,500.0,40000.0
39,40,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
51,52,2019-05-14,Central,Timothy,David,Television,53.0,1198.0,63494.0

### region wise avg salesman items sold

In [119]:
df.groupby(["Region","SalesMan","Item"])["Units"].agg(['mean',"sum"])

                                     mean    sum
Region  SalesMan  Item
Central David     Cell Phone    27.000000   27.0
                  Home Theater  63.000000  126.0
                  Television    30.000000  120.0
        John      Desk           2.000000    2.0
                  Home Theater  87.000000  174.0
                  Television    67.000000   67.0
        Luis      Home Theater  52.500000  105.0
                  Television    36.000000   36.0
                  Video Games   50.000000  100.0
        Shelli    Desk           5.000000    5.0
                  Home Theater  50.000000   50.0
                  Video Games   69.000000  138.0
        Sigal     Home Theater  28.000000   28.0
                  Television    90.000000   90.0
                  Video Games   55.000000   55.0
        Steven    Home Theater  28.000000   28.0
                  Television    40.000000   80.0
East    Alexander Cell Phone    64.000000   64.0
                  Home Theater  41.333333  124.0
                  Television    95.000000   95.0
                  Video Games   16.000000   16.0
        Diana     Cell Phone    96.000000  288.0
                  Home Theater  29.000000   29.0
        Karen     Cell Phone    15.000000   15.0
West    Michael   Home Theater  57.000000   57.0
                  Television    32.000000   32.0
        Stephen   Cell Phone    76.000000   76.0
                  Desk           3.000000    6.0
                  Home Theater   7.000000    7.0
                  Television          NaN    0.0

In [120]:
df.head(10)

,S.No.,OrderDate,Region,Manager,SalesMan,Item,Units,Unit_price,Sale_amt
0,1,2019-08-07,Central,Hermann,Shelli,Video Games,42.0,58.5,2457.0
1,2,2019-08-24,West,Timothy,Stephen,Desk,3.0,125.0,375.0
2,3,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
3,4,2018-01-06,East,Martha,Alexander,Television,95.0,1198.0,113810.0
4,5,2018-01-23,Central,Hermann,Shelli,Home Theater,50.0,500.0,25000.0
5,6,2018-02-09,Central,Hermann,Luis,Television,36.0,1198.0,43128.0
6,7,2018-02-26,Central,NaN,David,Cell Phone,27.0,225.0,6075.0
7,8,2018-03-15,West,Timothy,Stephen,Television,NaN,1198.0,0.0
8,9,2018-04-01,East,Martha,Alexander,Home Theater,60.0,500.0,30000.0
9,10,2018-04-18,NaN,Martha,Steven,Television,75.0,1198.0,89850.0

In [122]:
df[df.SalesMan == "David"]

,S.No.,OrderDate,Region,Manager,SalesMan,Item,Units,Unit_price,Sale_amt
2,3,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
6,7,2018-02-26,Central,NaN,David,Cell Phone,27.0,225.0,6075.0
25,26,2019-01-15,Central,Timothy,David,Home Theater,46.0,500.0,23000.0
32,33,2019-05-14,Central,Timothy,David,Television,53.0,1198.0,63494.0
33,34,2019-05-31,Central,Timothy,David,Home Theater,80.0,500.0,40000.0
39,40,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
51,52,2019-05-14,Central,Timothy,David,Television,53.0,1198.0,63494.0