## Data Cleaning & Preparation

- Handling Missing Data
- Duplicate Data
- Wrong Data Types
- Outlier Values Identify and Removal

## #1 Handling Missing Data

- Drop
- Fill

In [10]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
     ------------------------------------ 250.9/250.9 kB 699.6 kB/s eta 0:00:00
Collecting et-xmlfile
  Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
import pandas as pd

In [12]:
df = pd.read_excel("employee.xlsx")

In [13]:
df.head()

   Serial  Emp_ID Designation Department   Age    Salary
0       0    1101     Manager   Accounts  50.0  200000.0
1       1    1107     Officer         IT  30.0   80000.0
2       2    1203     Officer         HR  28.0       NaN
3       3    1005     Manager         HR  45.0  120000.0
4       4    2123  Office Boy   Accounts  27.0   45000.0

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Serial       26 non-null     int64
 1   Emp_ID       26 non-null     int64
 2   Designation  26 non-null     str
 3   Department   24 non-null     str
 4   Age          25 non-null     float64
 5   Salary       23 non-null     float64
dtypes: float64(2), int64(2), str(2)
memory usage: 1.3 KB

In [ ]:
df.isnull() #BOTH ARE SAME
# df.isna()

    Serial  Emp_ID  Designation  Department    Age  Salary
0    False   False        False       False  False   False
1    False   False        False       False  False   False
2    False   False        False       False  False    True
3    False   False        False       False  False   False
4    False   False        False       False  False   False
5    False   False        False        True  False   False
6    False   False        False       False   True   False
7    False   False        False       False  False   False
8    False   False        False       False  False    True
9    False   False        False       False  False   False
10   False   False        False       False  False   False
11   False   False        False       False  False   False
12   False   False        False       False  False   False
13   False   False        False       False  False   False
14   False   False        False       False  False   False
15   False   False        False        True  False    True
16   False   False        False       False  False   False
17   False   False        False       False  False   False
18   False   False        False       False  False   False
19   False   False        False       False  False   False
20   False   False        False       False  False   False
21   False   False        False       False  False   False
22   False   False        False       False  False   False
23   False   False        False       False  False   False
24   False   False        False       False  False   False
25   False   False        False       False  False   False

In [18]:
df.isnull().sum()

Serial         0
Emp_ID         0
Designation    0
Department     2
Age            1
Salary         3
dtype: int64

In [19]:
df.notnull().sum()

Serial         26
Emp_ID         26
Designation    26
Department     24
Age            25
Salary         23
dtype: int64

## Drop the Missing Values

In [22]:
df.dropna(axis=0) # DROP NULL ROWS

    Serial  Emp_ID Designation  Department   Age    Salary
0        0    1101     Manager    Accounts  50.0  200000.0
1        1    1107     Officer          IT  30.0   80000.0
3        3    1005     Manager          HR  45.0  120000.0
4        4    2123  Office Boy    Accounts  27.0   45000.0
7        7    1001     Officer          IT  25.0   75000.0
9        9    2156    Engineer  Production  45.0   89000.0
10      10    6543     Officer  Production  29.0  100000.0
11      11    3214  Accountant     Account  49.0  123000.0
12      12    2156    Engineer  Production  45.0   89000.0
13      13    1098     Officer          IT  25.0  100000.0
14      14    2912     Officer          IT  31.0   90000.0
16      16    2156    Engineer  Production  45.0   89000.0
17      17    2123  Office Boy    Accounts  27.0   45000.0
18      18    1005     Manager          HR  45.0  120000.0
19      19    2123  Office Boy    Accounts  27.0   45000.0
20      20    6543     Officer  Production  29.0  100000.0
21      21    3214  Accountant     Account  49.0  123000.0
22      22    2156    Engineer  Production  45.0   89000.0
23      23    1098     Officer          IT  25.0  100000.0
24      24    2156    Engineer  Production  45.0   89000.0
25      25    2123  Office Boy    Accounts  27.0   45000.0

In [ ]:
df.shape[0]

23

In [35]:
int(df.shape[1] * 0.90)

5

In [ ]:
df.dropna(axis=1 , how= "any")

In [37]:
df.dropna(axis=0 , thresh=int(df.shape[1] * 0.90))

    Serial  Emp_ID Designation  Department   Age    Salary
0        0    1101     Manager    Accounts  50.0  200000.0
1        1    1107     Officer          IT  30.0   80000.0
2        2    1203     Officer          HR  28.0       NaN
3        3    1005     Manager          HR  45.0  120000.0
4        4    2123  Office Boy    Accounts  27.0   45000.0
5        5    2451  Accountant         NaN  34.0  100000.0
6        6    1111  Accountant    Accounts   NaN  110000.0
7        7    1001     Officer          IT  25.0   75000.0
8        8    1234     Manager          IT  23.0       NaN
9        9    2156    Engineer  Production  45.0   89000.0
10      10    6543     Officer  Production  29.0  100000.0
11      11    3214  Accountant     Account  49.0  123000.0
12      12    2156    Engineer  Production  45.0   89000.0
13      13    1098     Officer          IT  25.0  100000.0
14      14    2912     Officer          IT  31.0   90000.0
16      16    2156    Engineer  Production  45.0   89000.0
17      17    2123  Office Boy    Accounts  27.0   45000.0
18      18    1005     Manager          HR  45.0  120000.0
19      19    2123  Office Boy    Accounts  27.0   45000.0
20      20    6543     Officer  Production  29.0  100000.0
21      21    3214  Accountant     Account  49.0  123000.0
22      22    2156    Engineer  Production  45.0   89000.0
23      23    1098     Officer          IT  25.0  100000.0
24      24    2156    Engineer  Production  45.0   89000.0
25      25    2123  Office Boy    Accounts  27.0   45000.0

## FIll Missing Values

In [47]:
df.Age.fillna(df.Age.mean())

0     50.0
1     30.0
2     28.0
3     45.0
4     27.0
5     34.0
6     35.0
7     25.0
8     23.0
9     45.0
10    29.0
11    49.0
12    45.0
13    25.0
14    31.0
15    25.0
16    45.0
17    27.0
18    45.0
19    27.0
20    29.0
21    49.0
22    45.0
23    25.0
24    45.0
25    27.0
Name: Age, dtype: float64

In [55]:
df.Department.mode()

0    Production
Name: Department, dtype: str

In [62]:
df.Department.mode()[0]

'Production'

In [ ]:
df.Department.fillna(df.Department.mode()[0])

0       Accounts
1             IT
2             HR
3             HR
4       Accounts
5     Production
6       Accounts
7             IT
8             IT
9     Production
10    Production
11       Account
12    Production
13            IT
14            IT
15    Production
16    Production
17      Accounts
18            HR
19      Accounts
20    Production
21       Account
22    Production
23            IT
24    Production
25      Accounts
Name: Department, dtype: str

In [64]:
df.Salary

0     200000.0
1      80000.0
2          NaN
3     120000.0
4      45000.0
5     100000.0
6     110000.0
7      75000.0
8          NaN
9      89000.0
10    100000.0
11    123000.0
12     89000.0
13    100000.0
14     90000.0
15         NaN
16     89000.0
17     45000.0
18    120000.0
19     45000.0
20    100000.0
21    123000.0
22     89000.0
23    100000.0
24     89000.0
25     45000.0
Name: Salary, dtype: float64

In [65]:
df.Salary.fillna(df.Salary.mean())

0     200000.000000
1      80000.000000
2      94173.913043
3     120000.000000
4      45000.000000
5     100000.000000
6     110000.000000
7      75000.000000
8      94173.913043
9      89000.000000
10    100000.000000
11    123000.000000
12     89000.000000
13    100000.000000
14     90000.000000
15     94173.913043
16     89000.000000
17     45000.000000
18    120000.000000
19     45000.000000
20    100000.000000
21    123000.000000
22     89000.000000
23    100000.000000
24     89000.000000
25     45000.000000
Name: Salary, dtype: float64

In [67]:
df.fillna(
    {
    "Age" : df.Age.fillna(df.Age.mean()),
    "Department" : df.Department.mode()[0],
    "Salary" : df.Salary.mean()
    }
)

    Serial  Emp_ID Designation  Department   Age         Salary
0        0    1101     Manager    Accounts  50.0  200000.000000
1        1    1107     Officer          IT  30.0   80000.000000
2        2    1203     Officer          HR  28.0   94173.913043
3        3    1005     Manager          HR  45.0  120000.000000
4        4    2123  Office Boy    Accounts  27.0   45000.000000
5        5    2451  Accountant  Production  34.0  100000.000000
6        6    1111  Accountant    Accounts  35.0  110000.000000
7        7    1001     Officer          IT  25.0   75000.000000
8        8    1234     Manager          IT  23.0   94173.913043
9        9    2156    Engineer  Production  45.0   89000.000000
10      10    6543     Officer  Production  29.0  100000.000000
11      11    3214  Accountant     Account  49.0  123000.000000
12      12    2156    Engineer  Production  45.0   89000.000000
13      13    1098     Officer          IT  25.0  100000.000000
14      14    2912     Officer          IT  31.0   90000.000000
15      15    1222     Officer  Production  25.0   94173.913043
16      16    2156    Engineer  Production  45.0   89000.000000
17      17    2123  Office Boy    Accounts  27.0   45000.000000
18      18    1005     Manager          HR  45.0  120000.000000
19      19    2123  Office Boy    Accounts  27.0   45000.000000
20      20    6543     Officer  Production  29.0  100000.000000
21      21    3214  Accountant     Account  49.0  123000.000000
22      22    2156    Engineer  Production  45.0   89000.000000
23      23    1098     Officer          IT  25.0  100000.000000
24      24    2156    Engineer  Production  45.0   89000.000000
25      25    2123  Office Boy    Accounts  27.0   45000.000000

In [102]:
df.Salary

TypeError: 'list' object is not callable