# Understanding Data Merging With Joins

|Types |  Description|
|------|-------------|
|INNER JOIN | Returns matching records from both tables.
|LEFT JOIN  | Returns all left table records and matched right table records, with nulls for missing matches.      |
|RIGHT JOIN | Returns all right table records and matched left table records, with nulls for missing matches.      |
|FULL JOIN  | Returns all records from both tables, matching where possible.                                       |
|CROSS JOIN | Produces a Cartesian product, matching every row from the first table with every row from the second.|
|SELF JOIN  | Joins a table to itself, treating it as two distinct tables.                                         |

In [1]:
import pandas as pd

In [34]:
data0 = pd.read_excel("test_data.xlsx",sheet_name = 0)
data1 = pd.read_excel("test_data.xlsx",sheet_name = 1)
data2 = pd.read_excel("test_data.xlsx",sheet_name = 2)

In [35]:
data0

   sales_man_id sales_man_name sales_man_city  product_id manager
0             1           Asad        Karachi         123   Jawed
1             2         Sumair         Lahore         123   Jawed
2             3         Farjad        Karachi         145   Najam
3             4         Hassan         Lahore         567   Najam
4             5          Nasir      Hyderabad         234   Jawed
5             6         Kashif      Hyderabad         234  Faisal
6             7           Sana         Lahore         567  Faisal
7             8         Fatima        Karachi         345   Najam
8             9       Abdullah        Karachi         123  Faisal

In [36]:
data1

    sales_man_id sales_man_name sales_man_city  product_id manager  Experience
0              1          Ahmed        Karachi         123   Jawed           2
1             22           Umer         Lahore         123   Jawed           3
2             33        Huzaifa        Karachi         145   Najam           4
3              4         Hassan         Lahore         567   Najam           5
4             55        Hussain      Hyderabad         234   Jawed           6
5             66            Ali      Hyderabad         234  Faisal           7
6             77          Sadaf         Lahore         567  Faisal           8
7             88          Kiran        Karachi         345   Najam           9
8             99            Ali        Karachi         123  Faisal           1
9            101           Asad      Hyderabad         432   Jawed           4
10           101           Asad      Hyderabad         432   Jawed           5

In [37]:
data2

   sales_man_id sales_man_name Region   Sales  Amount
0             2         Sumair       A    100   100000
1             5          Nasir       B    300   450000
2             7           Sana       C    234   125000
3            23           Sana       D    231   652000
4            45         Fatima       E    324   145000
5             1           Asad       F    123   825000
6             9       Abdullah       G    129   125000
7            56          Almas       H    345   325600
8             4         Hassan       I    400   895200

In [38]:
wholedata = (pd.concat([data0,data1,data2],ignore_index=True))

In [39]:
wholedata

,sales_man_id,sales_man_name,sales_man_city,product_id,manager,Experience,Region,Sales,Amount
0,1,Asad,Karachi,123.0,Jawed,NaN,NaN,NaN,NaN
1,2,Sumair,Lahore,123.0,Jawed,NaN,NaN,NaN,NaN
2,3,Farjad,Karachi,145.0,Najam,NaN,NaN,NaN,NaN
3,4,Hassan,Lahore,567.0,Najam,NaN,NaN,NaN,NaN
4,5,Nasir,Hyderabad,234.0,Jawed,NaN,NaN,NaN,NaN
5,6,Kashif,Hyderabad,234.0,Faisal,NaN,NaN,NaN,NaN
6,7,Sana,Lahore,567.0,Faisal,NaN,NaN,NaN,NaN
7,8,Fatima,Karachi,345.0,Najam,NaN,NaN,NaN,NaN
8,9,Abdullah,Karachi,123.0,Faisal,NaN,NaN,NaN,NaN
9,1,Ahmed,Karachi,123.0,Jawed,2.0,NaN,NaN,NaN
10,22,Umer,Lahore,123.0,Jawed,3.0,NaN,NaN,NaN
11,33,Huzaifa,Karachi,145.0,Najam,4.0,NaN,NaN,NaN
12,4,Hassan,Lahore,567.0,Najam,5.0,NaN,NaN,NaN
13,55,Hussain,Hyderabad,234.0,Jawed,6.0,NaN,NaN,NaN
14,66,Ali,Hyderabad,234.0,Faisal,7.0,NaN,NaN,NaN
15,77,Sadaf,Lahore,567.0,Faisal,8.0,NaN,NaN,NaN
16,88,Kiran,Karachi,345.0,Najam,9.0,NaN,NaN,NaN
17,99,Ali,Karachi,123.0,Faisal,1.0,NaN,NaN,NaN
18,101,Asad,Hyderabad,432.0,Jawed,4.0,NaN,NaN,NaN
19,101,Asad,Hyderabad,432.0,Jawed,5.0,NaN,NaN,NaN
20,2,Sumair,NaN,NaN,NaN,NaN,A,100.0,100000.0
21,5,Nasir,NaN,NaN,NaN,NaN,B,300.0,450000.0
22,7,Sana,NaN,NaN,NaN,NaN,C,234.0,125000.0
23,23,Sana,NaN,NaN,NaN,NaN,D,231.0,652000.0
24,45,Fatima,NaN,NaN,NaN,NaN,E,324.0,145000.0
25,1,Asad,NaN,NaN,NaN,NaN,F,123.0,825000.0
26,9,Abdullah,NaN,NaN,NaN,NaN,G,129.0,125000.0
27,56,Almas,NaN,NaN,NaN,NaN,H,345.0,325600.0
28,4,Hassan,NaN,NaN,NaN,NaN,I,400.0,895200.0

In [40]:
wholedata.head(16)

,sales_man_id,sales_man_name,sales_man_city,product_id,manager,Experience,Region,Sales,Amount
0,1,Asad,Karachi,123.0,Jawed,NaN,NaN,NaN,NaN
1,2,Sumair,Lahore,123.0,Jawed,NaN,NaN,NaN,NaN
2,3,Farjad,Karachi,145.0,Najam,NaN,NaN,NaN,NaN
3,4,Hassan,Lahore,567.0,Najam,NaN,NaN,NaN,NaN
4,5,Nasir,Hyderabad,234.0,Jawed,NaN,NaN,NaN,NaN
5,6,Kashif,Hyderabad,234.0,Faisal,NaN,NaN,NaN,NaN
6,7,Sana,Lahore,567.0,Faisal,NaN,NaN,NaN,NaN
7,8,Fatima,Karachi,345.0,Najam,NaN,NaN,NaN,NaN
8,9,Abdullah,Karachi,123.0,Faisal,NaN,NaN,NaN,NaN
9,1,Ahmed,Karachi,123.0,Jawed,2.0,NaN,NaN,NaN
10,22,Umer,Lahore,123.0,Jawed,3.0,NaN,NaN,NaN
11,33,Huzaifa,Karachi,145.0,Najam,4.0,NaN,NaN,NaN
12,4,Hassan,Lahore,567.0,Najam,5.0,NaN,NaN,NaN
13,55,Hussain,Hyderabad,234.0,Jawed,6.0,NaN,NaN,NaN
14,66,Ali,Hyderabad,234.0,Faisal,7.0,NaN,NaN,NaN
15,77,Sadaf,Lahore,567.0,Faisal,8.0,NaN,NaN,NaN

# Inner means intersection (Merge if on both table)

In [51]:
pd.merge(data0,data2, how= "inner",on="sales_man_id").drop(["sales_man_name_y"],axis=1)

,sales_man_id,sales_man_name_x,sales_man_city,product_id,manager,Region,Sales,Amount
0,1,Asad,Karachi,123,Jawed,F,123,825000
1,2,Sumair,Lahore,123,Jawed,A,100,100000
2,4,Hassan,Lahore,567,Najam,I,400,895200
3,5,Nasir,Hyderabad,234,Jawed,B,300,450000
4,7,Sana,Lahore,567,Faisal,C,234,125000
5,9,Abdullah,Karachi,123,Faisal,G,129,125000

# Outer means merge from both tables

In [42]:
pd.merge(data0,data2, how= "outer",on="sales_man_id")

,sales_man_id,sales_man_name_x,sales_man_city,product_id,manager,sales_man_name_y,Region,Sales,Amount
0,1,Asad,Karachi,123.0,Jawed,Asad,F,123.0,825000.0
1,2,Sumair,Lahore,123.0,Jawed,Sumair,A,100.0,100000.0
2,3,Farjad,Karachi,145.0,Najam,NaN,NaN,NaN,NaN
3,4,Hassan,Lahore,567.0,Najam,Hassan,I,400.0,895200.0
4,5,Nasir,Hyderabad,234.0,Jawed,Nasir,B,300.0,450000.0
5,6,Kashif,Hyderabad,234.0,Faisal,NaN,NaN,NaN,NaN
6,7,Sana,Lahore,567.0,Faisal,Sana,C,234.0,125000.0
7,8,Fatima,Karachi,345.0,Najam,NaN,NaN,NaN,NaN
8,9,Abdullah,Karachi,123.0,Faisal,Abdullah,G,129.0,125000.0
9,23,NaN,NaN,NaN,NaN,Sana,D,231.0,652000.0
10,45,NaN,NaN,NaN,NaN,Fatima,E,324.0,145000.0
11,56,NaN,NaN,NaN,NaN,Almas,H,345.0,325600.0

# Left means merge all from left table and matching from right table

In [43]:
pd.merge(data0,data2, how= "left",on="sales_man_id")

,sales_man_id,sales_man_name_x,sales_man_city,product_id,manager,sales_man_name_y,Region,Sales,Amount
0,1,Asad,Karachi,123,Jawed,Asad,F,123.0,825000.0
1,2,Sumair,Lahore,123,Jawed,Sumair,A,100.0,100000.0
2,3,Farjad,Karachi,145,Najam,NaN,NaN,NaN,NaN
3,4,Hassan,Lahore,567,Najam,Hassan,I,400.0,895200.0
4,5,Nasir,Hyderabad,234,Jawed,Nasir,B,300.0,450000.0
5,6,Kashif,Hyderabad,234,Faisal,NaN,NaN,NaN,NaN
6,7,Sana,Lahore,567,Faisal,Sana,C,234.0,125000.0
7,8,Fatima,Karachi,345,Najam,NaN,NaN,NaN,NaN
8,9,Abdullah,Karachi,123,Faisal,Abdullah,G,129.0,125000.0

# Right means merge all from left table and matching from right table

In [50]:
pd.merge(data0,data2, how= "right",on="sales_man_id")

,sales_man_id,sales_man_name_x,sales_man_city,product_id,manager,sales_man_name_y,Region,Sales,Amount
0,2,Sumair,Lahore,123.0,Jawed,Sumair,A,100,100000
1,5,Nasir,Hyderabad,234.0,Jawed,Nasir,B,300,450000
2,7,Sana,Lahore,567.0,Faisal,Sana,C,234,125000
3,23,NaN,NaN,NaN,NaN,Sana,D,231,652000
4,45,NaN,NaN,NaN,NaN,Fatima,E,324,145000
5,1,Asad,Karachi,123.0,Jawed,Asad,F,123,825000
6,9,Abdullah,Karachi,123.0,Faisal,Abdullah,G,129,125000
7,56,NaN,NaN,NaN,NaN,Almas,H,345,325600
8,4,Hassan,Lahore,567.0,Najam,Hassan,I,400,895200

# Time Series Data

# Date and Time Data Types And Tools

In [53]:
from datetime import datetime

In [58]:
today = datetime.now()

In [59]:
today.date()

datetime.date(2026, 7, 5)

In [60]:
today.time()

datetime.time(17, 8, 28, 164925)

In [62]:
today.day

5

In [63]:
today.month

7

In [64]:
today.year

2026

In [67]:
today.weekday()

6

In [74]:
print(today.strftime("%A"))

Sunday

In [78]:
today.strftime("")

''

In [ ]:
delta = datetime(2011, 1, 7) - datetime(2008, 6, 24, 8, 15)

In [ ]:
delta

datetime.timedelta(days=926, seconds=56700)

In [ ]:
delta.days

926

In [82]:
from datetime import timedelta
start = datetime(2011, 1, 7)
start + timedelta(12)

datetime.datetime(2011, 1, 19, 0, 0)

# Converting Between String and Datetime

In [88]:
dob = datetime(2000,7,5)

In [93]:
dob.strftime("%d-%m-%Y")

'05-07-2000'

In [94]:
value = "2011-01-03"

In [96]:
dob.strptime(value,"%Y-%m-%d")

datetime.datetime(2011, 1, 3, 0, 0)

In [101]:
datestr = ["7/6/2011","8/6/2011"]

In [104]:
[datetime.strptime(x, "%m/%d/%Y") for x in datestr]

[datetime.datetime(2011, 7, 6, 0, 0), datetime.datetime(2011, 8, 6, 0, 0)]

In [105]:
dates = [
    datetime(2011,1,1),
    datetime(2011,1,12),
    datetime(2011,1,13),
    datetime(2011,1,14),
    datetime(2011,1,15),
    datetime(2011,1,16),
    datetime(2011,1,17),
]

In [106]:
import numpy as np

In [107]:
ts = pd.Series(np.random.randn(7),index = dates)

In [108]:
ts

2011-01-01   -1.515856
2011-01-12    0.503504
2011-01-13    0.602914
2011-01-14    0.228214
2011-01-15    0.798767
2011-01-16   -0.299132
2011-01-17   -0.368606
dtype: float64

In [110]:
longer_ts = pd.Series(np.random.randn(1000), index = pd.date_range("2000/1/1",periods=1000))

In [111]:
longer_ts

2000-01-01   -0.062861
2000-01-02    0.560883
2000-01-03   -0.195218
2000-01-04    0.620013
2000-01-05    0.400922
                ...
2002-09-22   -0.633290
2002-09-23   -1.098579
2002-09-24    0.349078
2002-09-25    0.154635
2002-09-26   -0.425651
Freq: D, Length: 1000, dtype: float64

In [112]:
longer_ts["2001-01-03":"2001-05-03"]

2001-01-03    0.451409
2001-01-04   -0.252644
2001-01-05    0.331346
2001-01-06    0.269649
2001-01-07    1.470534
                ...
2001-04-29   -0.024990
2001-04-30    0.647962
2001-05-01   -0.116009
2001-05-02   -0.320128
2001-05-03    0.640481
Freq: D, Length: 121, dtype: float64

In [115]:
import random as rd

In [331]:
r = rd.randint(5,15)
r

11

In [180]:
r

6