In [35]:
import pandas as pd

In [36]:
df = pd.read_csv("Loan.csv")

In [37]:
df.head()

,customer_id,age,occupation_status,years_employed,annual_income,credit_score,credit_history_years,savings_assets,current_debt,defaults_on_file,delinquencies_last_2yrs,derogatory_marks,product_type,loan_intent,loan_amount,interest_rate,debt_to_income_ratio,loan_to_income_ratio,payment_to_income_ratio,loan_status
0,CUST100000,40,Employed,17.2,25579,692,5.3,895,10820,0,0,0,Credit Card,Business,600,17.02,0.423,0.023,0.008,1
1,CUST100001,33,Employed,7.3,43087,627,3.5,169,16550,0,1,0,Personal Loan,Home Improvement,53300,14.10,0.384,1.237,0.412,0
2,CUST100002,42,Student,1.1,20840,689,8.4,17,7852,0,0,0,Credit Card,Debt Consolidation,2100,18.33,0.377,0.101,0.034,1
3,CUST100003,53,Student,0.5,29147,692,9.8,1480,11603,0,1,0,Credit Card,Business,2900,18.74,0.398,0.099,0.033,1
4,CUST100004,32,Employed,12.5,63657,630,7.2,209,12424,0,0,0,Personal Loan,Education,99600,13.92,0.195,1.565,0.522,1

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              50000 non-null  str
 1   age                      50000 non-null  int64
 2   occupation_status        50000 non-null  str
 3   years_employed           50000 non-null  float64
 4   annual_income            50000 non-null  int64
 5   credit_score             50000 non-null  int64
 6   credit_history_years     50000 non-null  float64
 7   savings_assets           50000 non-null  int64
 8   current_debt             50000 non-null  int64
 9   defaults_on_file         50000 non-null  int64
 10  delinquencies_last_2yrs  50000 non-null  int64
 11  derogatory_marks         50000 non-null  int64
 12  product_type             50000 non-null  str
 13  loan_intent              50000 non-null  str
 14  loan_amount              50000 non-null  int64
 15  interest_rate            50000 non-null  float64
 16  debt_to_income_ratio     50000 non-null  float64
 17  loan_to_income_ratio     50000 non-null  float64
 18  payment_to_income_ratio  50000 non-null  float64
 19  loan_status              50000 non-null  int64
dtypes: float64(6), int64(10), str(4)
memory usage: 7.6 MB

In [39]:
df.isnull().sum()

customer_id                0
age                        0
occupation_status          0
years_employed             0
annual_income              0
credit_score               0
credit_history_years       0
savings_assets             0
current_debt               0
defaults_on_file           0
delinquencies_last_2yrs    0
derogatory_marks           0
product_type               0
loan_intent                0
loan_amount                0
interest_rate              0
debt_to_income_ratio       0
loan_to_income_ratio       0
payment_to_income_ratio    0
loan_status                0
dtype: int64

In [40]:
df.duplicated().sum()

np.int64(0)

In [41]:
df.defaults_on_file.unique()

array([0, 1])

In [42]:
df.head()

,customer_id,age,occupation_status,years_employed,annual_income,credit_score,credit_history_years,savings_assets,current_debt,defaults_on_file,delinquencies_last_2yrs,derogatory_marks,product_type,loan_intent,loan_amount,interest_rate,debt_to_income_ratio,loan_to_income_ratio,payment_to_income_ratio,loan_status
0,CUST100000,40,Employed,17.2,25579,692,5.3,895,10820,0,0,0,Credit Card,Business,600,17.02,0.423,0.023,0.008,1
1,CUST100001,33,Employed,7.3,43087,627,3.5,169,16550,0,1,0,Personal Loan,Home Improvement,53300,14.10,0.384,1.237,0.412,0
2,CUST100002,42,Student,1.1,20840,689,8.4,17,7852,0,0,0,Credit Card,Debt Consolidation,2100,18.33,0.377,0.101,0.034,1
3,CUST100003,53,Student,0.5,29147,692,9.8,1480,11603,0,1,0,Credit Card,Business,2900,18.74,0.398,0.099,0.033,1
4,CUST100004,32,Employed,12.5,63657,630,7.2,209,12424,0,0,0,Personal Loan,Education,99600,13.92,0.195,1.565,0.522,1

In [43]:
df = df.drop("customer_id",axis=1)

In [51]:
x = df.select_dtypes(include=["object","category"]).columns
y = df.select_dtypes(include=["int","float"]).columns

C:\Users\SMIT\AppData\Local\Temp\ipykernel_24024\2153583545.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  x = df.select_dtypes(include=["object","category"]).columns

In [52]:
x

Index(['occupation_status', 'product_type', 'loan_intent'], dtype='str')

In [53]:
y

Index(['age', 'years_employed', 'annual_income', 'credit_score',
       'credit_history_years', 'savings_assets', 'current_debt',
       'defaults_on_file', 'delinquencies_last_2yrs', 'derogatory_marks',
       'loan_amount', 'interest_rate', 'debt_to_income_ratio',
       'loan_to_income_ratio', 'payment_to_income_ratio', 'loan_status'],
      dtype='str')

In [54]:
from sklearn.preprocessing import OneHotEncoder

In [55]:
encoder = OneHotEncoder()

In [56]:
x

Index(['occupation_status', 'product_type', 'loan_intent'], dtype='str')

In [63]:
x_encoded = encoder.fit_transform(df[x]).toarray()

In [64]:
encoder.get_feature_names_out()

array(['occupation_status_Employed', 'occupation_status_Self-Employed',
       'occupation_status_Student', 'product_type_Credit Card',
       'product_type_Line of Credit', 'product_type_Personal Loan',
       'loan_intent_Business', 'loan_intent_Debt Consolidation',
       'loan_intent_Education', 'loan_intent_Home Improvement',
       'loan_intent_Medical', 'loan_intent_Personal'], dtype=object)

In [65]:
x_encoded

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.]], shape=(50000, 12))

In [66]:
x_encoded = pd.DataFrame(data=x_encoded,columns=encoder.get_feature_names_out())

In [67]:
x_encoded

,occupation_status_Employed,occupation_status_Self-Employed,occupation_status_Student,product_type_Credit Card,product_type_Line of Credit,product_type_Personal Loan,loan_intent_Business,loan_intent_Debt Consolidation,loan_intent_Education,loan_intent_Home Improvement,loan_intent_Medical,loan_intent_Personal
0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
49995,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
49996,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
49997,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
49998,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
49999,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [68]:
from sklearn.preprocessing import StandardScaler

In [69]:
scaler = StandardScaler()

In [70]:
y_scaled = scaler.fit_transform(df[y])

In [71]:
y_scaled

array([[ 0.45356332,  1.28022932, -0.75034511, ..., -1.45775792,
        -1.45552889,  0.90369377],
       [-0.17601848, -0.02034519, -0.21378654, ...,  1.14860675,
         1.14644826, -1.10656954],
       [ 0.63344384, -0.8348464 , -0.89557878, ..., -1.29029792,
        -1.28807491,  0.90369377],
       ...,
       [ 0.54350358, -0.3487731 , -0.95984445, ...,  0.55390904,
         0.55391881, -1.10656954],
       [ 0.27368281, -0.92680621, -1.00559964, ..., -1.33323638,
        -1.33315867, -1.10656954],
       [ 1.62278667,  1.28022932, -0.09622664, ...,  0.36927365,
         0.36714323,  0.90369377]], shape=(50000, 16))

In [72]:
y_scaled = pd.DataFrame(data=y_scaled,columns=scaler.get_feature_names_out())

In [73]:
y_scaled

,age,years_employed,annual_income,credit_score,credit_history_years,savings_assets,current_debt,defaults_on_file,delinquencies_last_2yrs,derogatory_marks,loan_amount,interest_rate,debt_to_income_ratio,loan_to_income_ratio,payment_to_income_ratio,loan_status
0,0.453563,1.280229,-0.750345,0.747482,-0.397958,-0.204093,-0.262046,-0.237701,-0.656347,-0.357489,-1.242226,0.374003,0.859129,-1.457758,-1.455529,0.903694
1,-0.176018,-0.020345,-0.213787,-0.256675,-0.647698,-0.258959,0.170615,-0.237701,0.527028,-0.357489,0.775700,-0.343811,0.615051,1.148607,1.146448,-1.106570
2,0.633444,-0.834846,-0.895579,0.701137,0.032151,-0.270446,-0.486154,-0.237701,-0.656347,-0.357489,-1.184790,0.696037,0.571242,-1.290298,-1.288075,0.903694
3,1.622787,-0.913669,-0.640998,0.747482,0.226393,-0.159883,-0.202923,-0.237701,0.527028,-0.357489,-1.154157,0.796826,0.702669,-1.294592,-1.294515,0.903694
4,-0.265959,0.662785,0.416612,-0.210330,-0.134343,-0.255936,-0.140931,-0.237701,-0.656347,-0.357489,2.548565,-0.388060,-0.567789,1.852798,1.854907,0.903694
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,0.003862,-0.414459,-0.325278,-1.137244,1.128234,-0.186561,-0.506994,-0.237701,-0.656347,-0.357489,0.373647,1.428601,-0.586564,0.822274,0.824421,-1.106570
49996,-0.086078,-0.401322,-0.906121,0.438511,0.614879,-0.160035,-0.605155,4.206968,-0.656347,-0.357489,-1.119695,0.632122,0.126895,-1.109956,-1.107740,-1.106570
49997,0.543504,-0.348773,-0.959844,1.164594,0.268017,-0.270446,-0.298970,-0.237701,-0.656347,-0.357489,-0.575966,0.479709,1.660206,0.553909,0.553919,-1.106570
49998,0.273683,-0.926806,-1.005600,-0.163984,-0.952937,-0.271353,-0.491666,-0.237701,-0.656347,2.063865,-1.211593,-0.193857,1.034364,-1.333236,-1.333159,-1.106570
49999,1.622787,1.280229,-0.096227,0.793828,0.947866,0.357942,-0.878569,-0.237701,0.527028,-0.357489,0.304723,-0.764176,-1.431450,0.369274,0.367143,0.903694

In [74]:
df1 = pd.concat([y_scaled,x_encoded],axis=1)

In [75]:
df1

,age,years_employed,annual_income,credit_score,credit_history_years,savings_assets,current_debt,defaults_on_file,delinquencies_last_2yrs,derogatory_marks,...,occupation_status_Student,product_type_Credit Card,product_type_Line of Credit,product_type_Personal Loan,loan_intent_Business,loan_intent_Debt Consolidation,loan_intent_Education,loan_intent_Home Improvement,loan_intent_Medical,loan_intent_Personal
0,0.453563,1.280229,-0.750345,0.747482,-0.397958,-0.204093,-0.262046,-0.237701,-0.656347,-0.357489,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,-0.176018,-0.020345,-0.213787,-0.256675,-0.647698,-0.258959,0.170615,-0.237701,0.527028,-0.357489,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.633444,-0.834846,-0.895579,0.701137,0.032151,-0.270446,-0.486154,-0.237701,-0.656347,-0.357489,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,1.622787,-0.913669,-0.640998,0.747482,0.226393,-0.159883,-0.202923,-0.237701,0.527028,-0.357489,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,-0.265959,0.662785,0.416612,-0.210330,-0.134343,-0.255936,-0.140931,-0.237701,-0.656347,-0.357489,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,0.003862,-0.414459,-0.325278,-1.137244,1.128234,-0.186561,-0.506994,-0.237701,-0.656347,-0.357489,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
49996,-0.086078,-0.401322,-0.906121,0.438511,0.614879,-0.160035,-0.605155,4.206968,-0.656347,-0.357489,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
49997,0.543504,-0.348773,-0.959844,1.164594,0.268017,-0.270446,-0.298970,-0.237701,-0.656347,-0.357489,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
49998,0.273683,-0.926806,-1.005600,-0.163984,-0.952937,-0.271353,-0.491666,-0.237701,-0.656347,2.063865,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
49999,1.622787,1.280229,-0.096227,0.793828,0.947866,0.357942,-0.878569,-0.237701,0.527028,-0.357489,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [86]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 28 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   age                              50000 non-null  float64
 1   years_employed                   50000 non-null  float64
 2   annual_income                    50000 non-null  float64
 3   credit_score                     50000 non-null  float64
 4   credit_history_years             50000 non-null  float64
 5   savings_assets                   50000 non-null  float64
 6   current_debt                     50000 non-null  float64
 7   defaults_on_file                 50000 non-null  float64
 8   delinquencies_last_2yrs          50000 non-null  float64
 9   derogatory_marks                 50000 non-null  float64
 10  loan_amount                      50000 non-null  float64
 11  interest_rate                    50000 non-null  float64
 12  debt_to_income_ratio             50000 non-null  float64
 13  loan_to_income_ratio             50000 non-null  float64
 14  payment_to_income_ratio          50000 non-null  float64
 15  loan_status                      50000 non-null  float64
 16  occupation_status_Employed       50000 non-null  float64
 17  occupation_status_Self-Employed  50000 non-null  float64
 18  occupation_status_Student        50000 non-null  float64
 19  product_type_Credit Card         50000 non-null  float64
 20  product_type_Line of Credit      50000 non-null  float64
 21  product_type_Personal Loan       50000 non-null  float64
 22  loan_intent_Business             50000 non-null  float64
 23  loan_intent_Debt Consolidation   50000 non-null  float64
 24  loan_intent_Education            50000 non-null  float64
 25  loan_intent_Home Improvement     50000 non-null  float64
 26  loan_intent_Medical              50000 non-null  float64
 27  loan_intent_Personal             50000 non-null  float64
dtypes: float64(28)
memory usage: 10.7 MB

In [87]:
df1.drop("loan_status",axis=1,inplace=True)

In [89]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 27 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   age                              50000 non-null  float64
 1   years_employed                   50000 non-null  float64
 2   annual_income                    50000 non-null  float64
 3   credit_score                     50000 non-null  float64
 4   credit_history_years             50000 non-null  float64
 5   savings_assets                   50000 non-null  float64
 6   current_debt                     50000 non-null  float64
 7   defaults_on_file                 50000 non-null  float64
 8   delinquencies_last_2yrs          50000 non-null  float64
 9   derogatory_marks                 50000 non-null  float64
 10  loan_amount                      50000 non-null  float64
 11  interest_rate                    50000 non-null  float64
 12  debt_to_income_ratio             50000 non-null  float64
 13  loan_to_income_ratio             50000 non-null  float64
 14  payment_to_income_ratio          50000 non-null  float64
 15  occupation_status_Employed       50000 non-null  float64
 16  occupation_status_Self-Employed  50000 non-null  float64
 17  occupation_status_Student        50000 non-null  float64
 18  product_type_Credit Card         50000 non-null  float64
 19  product_type_Line of Credit      50000 non-null  float64
 20  product_type_Personal Loan       50000 non-null  float64
 21  loan_intent_Business             50000 non-null  float64
 22  loan_intent_Debt Consolidation   50000 non-null  float64
 23  loan_intent_Education            50000 non-null  float64
 24  loan_intent_Home Improvement     50000 non-null  float64
 25  loan_intent_Medical              50000 non-null  float64
 26  loan_intent_Personal             50000 non-null  float64
dtypes: float64(27)
memory usage: 10.3 MB

In [90]:
X = df1
y = df.loan_status

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [91]:
# X contains your features, y contains your target variable
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [92]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X_train,y_train)

LogisticRegression()

In [93]:
y_pred = log_reg.predict(X_train)

In [94]:
from sklearn.metrics import classification_report

In [95]:
print(classification_report(y_train,y_pred))

              precision    recall  f1-score   support

           0       0.86      0.84      0.85     17968
           1       0.87      0.89      0.88     22032

    accuracy                           0.87     40000
   macro avg       0.87      0.86      0.86     40000
weighted avg       0.87      0.87      0.87     40000